export const AVAILABLE_APPOINTMENTS_REQUEST = 'AVAILABLE_APPOINTMENTS_REQUEST'
export const AVAILABLE_APPOINTMENTS_SUCCESS = 'AVAILABLE_APPOINTMENTS_SUCCESS'
export const AVAILABLE_APPOINTMENTS_FAIL = 'AVAILABLE_APPOINTMENTS_FAIL'
export const AVAILABLE_APPOINTMENTS_RESET = 'AVAILABLE_APPOINTMENTS_RESET'

export const APPOINTMENT_CREATE_REQUEST = 'APPOINTMENT_CREATE_REQUEST'
export const APPOINTMENT_CREATE_SUCCESS = 'APPOINTMENT_CREATE_SUCCESS'
export const APPOINTMENT_CREATE_FAIL = 'APPOINTMENT_CREATE_FAIL'
